service:
  name: try-not-to-laugh-challenge

plugins:
  - serverless-webpack
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  environment:
    TARGET_REGION: ${self:provider.region}

package:
  individually: true
  exclude:
    - node_modules/**/aws_sdk/**
