service:
  name: ${self:custom.appname}

plugins:
  - serverless-webpack
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  environment:
    TARGET_REGION: ${self:provider.region}

    SCORE_HAPPY_MULTIPLIER: 3.2
    SCORE_SURPRISED_MULTIPLIER: 2.2
    SCORE_DISGUSTED_MULTIPLIER: 1.2
    SCORE_CALM_MULTIPLIER: 1.0
    SCORE_SAD_MULTIPLIER: 0.1
    SCORE_ANGRY_MULTIPLIER: 0.4
    SCORE_CONFUSED_MULTIPLIER: 0.1

    DDB_PLAYERS:
      Ref: PlayersTable
    DDB_PHOTOSCORES:
      Ref: PhotoScoresTable

    REKOG_MINIMUM_FACE_SIZE: 0.25

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:*
        - s3:*
        - dynamodb:*
      Resource:
        - '*'

custom:
  appname: try-not-to-laugh-challenge
  appshortname: tntlc-${self:provider.stage}

functions:
  getPhotoScore:
    handler: functions/get-photo-score/index.handler
    events:
      - s3:
          bucket: ${self:custom.appshortname}-photobucket
          event: s3:ObjectCreated:*

package:
  individually: true
  exclude:
    - node_modules/**/aws_sdk/**

resources:
  - ${file(resources/iam.yml)}
  - ${file(resources/ddb.yml)}
  - ${file(resources/cognito.yml)}
  - ${file(resources/appsync.yml)}
